name: CI

#on: [push]

# 在master分支发生push事件时触发。
on:
  push:
    branches:
      - master

env: # 设置环境变量
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）

jobs:
  build: # 自定义名称
    runs-on: ubuntu-latest # 运行在虚拟机环境ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      # 1.检出仓库
      - name: Checkout
        uses: actions/checkout@master # 使用的动作。格式：userName/repoName。 官方actions库：https://github.com/actions
        with:
          persist-credentials: false

      # 2.安装nodejs
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      # 3.生成静态文件
      - name: Build
        run: npm install && npm run build

      # 4.部署到 GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REPOSITORY_NAME: 954118124/blog
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist #注意这里是 npm run build 生成静态资源的路径：docs/.vuepress/dist

      # 5、部署到 腾讯云 服务器
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.LOUIS_ACCESS }}
          ARGS: "-avz --delete"
          SOURCE: "docs/.vuepress/dist"
          REMOTE_HOST: 43.138.216.21
          REMOTE_USER: root
          TARGET: /louis/blog/

#      # 5.同步到 gitee 的仓库
#      - name: Sync to Gitee
#        uses: wearerequired/git-mirror-action@master
#        env:
#          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
#          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#        with:
#          # GitHub 源仓库地址
#          source-repo: git@github.com:954118124/blog.git
#          # Gitee 目标仓库地址
#          destination-repo: git@gitee.com:louisccy/louisccy.git
#
#      # 6.部署到 Gitee Pages
#      - name: Build Gitee Pages
#        uses: yanglbme/gitee-pages-action@main
#        with:
#          # Gitee 用户名
#          gitee-username: louisccy
#          # Settings->Secrets 配置 GITEE_PASSWORD
#          gitee-password: ${{ secrets.GITEE_PASSWORD }}
#          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
#          gitee-repo: louisccy/louisccy
#          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
#          branch: gh-pages

